"""PDF generation for Kundli birth chart and match reports."""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

_STYLES = getSampleStyleSheet()
_TITLE = ParagraphStyle("KTitle", parent=_STYLES["Heading1"], fontSize=18, spaceAfter=4)
_H2 = ParagraphStyle("KH2", parent=_STYLES["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#c07010"))
_BODY = ParagraphStyle("KBody", parent=_STYLES["Normal"], fontSize=9, leading=13)
_SMALL = ParagraphStyle("KSmall", parent=_STYLES["Normal"], fontSize=8, leading=11, textColor=colors.grey)

_TBL_STYLE = TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0e8d8")),
    ("FONTSIZE", (0, 0), (-1, 0), 9),
    ("FONTSIZE", (0, 1), (-1, -1), 8),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
    ("TOPPADDING", (0, 0), (-1, -1), 3),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ("LEFTPADDING", (0, 0), (-1, -1), 4),
    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
])

PLANET_EN = {
    "Surya": "Sun", "Chandra": "Moon", "Mangal": "Mars", "Budh": "Mercury",
    "Guru": "Jupiter", "Shukra": "Venus", "Shani": "Saturn", "Rahu": "Rahu", "Ketu": "Ketu",
}


def generate_kundli_pdf(ctx: dict) -> bytes:
    """Generate a PDF for a birth chart from stored chart context."""
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15 * mm, bottomMargin=15 * mm)
    story = []

    # Header
    story.append(Paragraph("Kundli — Vedic Birth Chart", _TITLE))
    birth = ctx.get("birth_dt", "")
    loc = ctx.get("location", "")
    if birth:
        story.append(Paragraph(f"<b>Date:</b> {birth} &nbsp; <b>Place:</b> {loc}", _BODY))
    lagna = ctx["houses"][0]
    story.append(Paragraph(f"<b>Lagna:</b> {lagna['sign']} {lagna['degree']:.2f}°", _BODY))
    story.append(Spacer(1, 6))

    # Planets table
    story.append(Paragraph("Planetary Positions", _H2))
    data = [["Planet", "Sign", "Degree", "Nakshatra", "Pada", "Retro"]]
    for p in ctx["planets"]:
        retro = "R" if p.get("retrograde") else ""
        data.append([f"{p['planet']} ({PLANET_EN.get(p['planet'], '')})", p["sign"], f"{p['degree']:.2f}°", p["nakshatra"], str(p["pada"]), retro])
    story.append(Table(data, hAlign="LEFT", style=_TBL_STYLE))

    # Houses table
    story.append(Paragraph("House Cusps", _H2))
    data = [["House", "Sign", "Degree"]]
    for h in ctx["houses"]:
        data.append([str(h["house"]), h["sign"], f"{h['degree']:.2f}°"])
    story.append(Table(data, hAlign="LEFT", style=_TBL_STYLE))

    # Yogas
    yogas = ctx.get("yogas", [])
    if yogas:
        story.append(Paragraph("Yogas", _H2))
        for y in yogas:
            story.append(Paragraph(f"<b>{y['name']}</b> — {y['desc']}", _BODY))

    # Doshas
    doshas = ctx.get("doshas", [])
    if doshas:
        story.append(Paragraph("Doshas", _H2))
        for d in doshas:
            status = "⚠ Present" if d["present"] else "✓ Not present"
            story.append(Paragraph(f"<b>{d['name']}</b>: {status} — {d['detail']}", _BODY))

    # Dasha timeline (top level only)
    story.append(Paragraph("Vimshottari Dasha", _H2))
    data = [["Lord", "Start", "End", "Years"]]
    for d in ctx["dashas"]:
        data.append([d["lord"], d["start"].strftime("%d %b %Y"), d["end"].strftime("%d %b %Y"), str(d["years"])])
    story.append(Table(data, hAlign="LEFT", style=_TBL_STYLE))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by Kundli · Calculations powered by Swiss Ephemeris", _SMALL))

    doc.build(story)
    return buf.getvalue()


def generate_match_pdf(result: dict, people: list) -> bytes:
    """Generate a PDF for Ashtakoota match result."""
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15 * mm, bottomMargin=15 * mm)
    story = []

    story.append(Paragraph("Kundli Match — Ashtakoota Gun Milan", _TITLE))
    story.append(Paragraph(
        f"<b>{people[0]['name']}</b> ({people[0]['moon_sign']} / {people[0]['nakshatra']}) &nbsp; ⟷ &nbsp; "
        f"<b>{people[1]['name']}</b> ({people[1]['moon_sign']} / {people[1]['nakshatra']})", _BODY))
    story.append(Spacer(1, 4))

    # Score
    total = result["total"]
    if total >= 32:
        verdict = "Excellent match"
    elif total >= 24:
        verdict = "Good match — recommended"
    elif total >= 18:
        verdict = "Average — proceed with caution"
    else:
        verdict = "Not recommended"
    story.append(Paragraph(f"<b>Score: {total} / {result['max']}</b> — {verdict}", _BODY))
    story.append(Spacer(1, 6))

    # Koota table
    story.append(Paragraph("Koota Breakdown", _H2))
    data = [["Koota", people[0]["name"], people[1]["name"], "Score"]]
    for k in result["kootas"]:
        data.append([f"{k['name']}\n{k['description']}", k["boy"], k["girl"], f"{k['score']}/{k['max']}"])
    data.append(["Total", "", "", f"{result['total']}/{result['max']}"])
    story.append(Table(data, hAlign="LEFT", style=_TBL_STYLE))

    # Doshas
    warnings = []
    nadi = result["kootas"][7]
    bhakoot = result["kootas"][6]
    if nadi["score"] == 0:
        warnings.append(f"Nadi Dosha — Both have {nadi['boy']} Nadi.")
    if bhakoot["score"] == 0:
        warnings.append(f"Bhakoot Dosha — {bhakoot['boy']} and {bhakoot['girl']} are in an unfavorable axis.")
    for p in people:
        if p.get("manglik"):
            warnings.append(f"Manglik Dosha — {p['name']} has Mars in House {p.get('mars_house')}.")
    if warnings:
        story.append(Paragraph("Doshas", _H2))
        for w in warnings:
            story.append(Paragraph(f"⚠ {w}", _BODY))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by Kundli · Calculations powered by Swiss Ephemeris", _SMALL))

    doc.build(story)
    return buf.getvalue()
